dist: bionic
language: java
jdk: oraclejdk14

install:
  - mvn install -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)


cache:
  directories:
    - $HOME/.m2
